version: "3"

services:
  proxigram:
    container_name: proxigram
    restart: unless-stopped
    env_file: .env
    build: .
    ports:
      - 3000:3000

  redis:
    image: redis:7-bookworm
    restart: unless-stopped